version: "3.9"
services:
  db:
    image: postgres:16-alpine
    container_name: linkshortener_db
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: linkshortener
    volumes:
      - db_data:/var/lib/postgresql/data
    ports:
      - "55432:5432"

  backend:
    build:
      context: ./backend
    container_name: linkshortener_backend
    ports:
      - "3000:3000"
    environment:
      DATABASE_URL: postgres://postgres:password@db:5432/linkshortener
      NODE_ENV: production
    depends_on:
      - db

  frontend:
    build:
      context: ./frontend
    container_name: linkshortener_frontend
    ports:
      - "8000:80"
    environment:
      VITE_API_URL: http://localhost:3000
    depends_on:
      - backend

volumes:
  db_data:
