---
apiVersion: v1
kind: Secret
metadata:
  name: linkshortener-secrets
  namespace: linkshortener
type: Opaque
stringData:
  POSTGRES_USER: linkshortener_user
  POSTGRES_PASSWORD: SuperSecurePassword123!
  POSTGRES_DB: linkshortener_db
  
  JWT_SECRET: eW91ci1zdXBlci1zZWNyZXQtand0LWtleS1jaGFuZ2UtdGhpcy1pbi1wcm9kdWN0aW9uCg==
  
  REDIS_PASSWORD: ""
