---
apiVersion: v1
kind: Service
metadata:
  name: linkshortener-backend
  namespace: linkshortener
  labels:
    app: linkshortener-backend
spec:
  type: NodePort
  ports:
  - port: 3000
    targetPort: 3000
    nodePort: 30001
    protocol: TCP
    name: http
  selector:
    app: linkshortener-backend
  sessionAffinity: ClientIP